# Generated by Django 3.0.5 on 2020-04-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PerformanceData',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TestSequence',
        ),
        migrations.DeleteModel(
            name='TestStandard',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
