# Generated by Django 3.0.4 on 2020-04-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0002_auto_20200404_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='locationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Location'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='modelnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standardid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestStandard'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='modelnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='sequenceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestSequence'),
        ),
        migrations.AlterField(
            model_name='service',
            name='standardid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestStandard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client'),
        ),
    ]
