# Generated by Django 3.0.4 on 2020-04-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0004_remove_certificate_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='modelnumber',
        ),
        migrations.RemoveField(
            model_name='performancedata',
            name='sequenceid',
        ),
        migrations.RemoveField(
            model_name='service',
            name='standardid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clientid',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PerformanceData',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TestSequence',
        ),
        migrations.DeleteModel(
            name='TestStandard',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
