# Generated by Django 3.0.5 on 2020-05-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=35)),
                ('reportnumber', models.CharField(max_length=35)),
                ('issuedate', models.CharField(max_length=35)),
                ('standardid', models.CharField(max_length=35)),
                ('locationid', models.CharField(max_length=35)),
                ('modelnumber', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=35)),
                ('clienttype', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=35)),
                ('address2', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('postalcode', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
                ('phonenumber', models.CharField(max_length=35)),
                ('faxnumber', models.CharField(max_length=35)),
                ('clientid', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelnumber', models.CharField(max_length=35)),
                ('sequenceid', models.CharField(max_length=35)),
                ('maxsystemvoltage', models.CharField(max_length=35)),
                ('voc', models.FloatField()),
                ('isc', models.FloatField()),
                ('vmp', models.FloatField()),
                ('imp', models.FloatField()),
                ('pmp', models.FloatField()),
                ('ff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelnumber', models.CharField(max_length=35)),
                ('productname', models.CharField(max_length=35)),
                ('celltechnology', models.CharField(max_length=35)),
                ('cellmanufacturer', models.CharField(max_length=35)),
                ('numberofcells', models.IntegerField()),
                ('numberofcellsinseries', models.IntegerField()),
                ('numberofseriesinstrings', models.IntegerField()),
                ('numberofdiodes', models.IntegerField()),
                ('productlength', models.FloatField()),
                ('productwidth', models.FloatField()),
                ('productweight', models.FloatField()),
                ('superstatetype', models.CharField(max_length=35)),
                ('superstatemanufacturer', models.CharField(max_length=35)),
                ('substratetype', models.CharField(max_length=35)),
                ('substratemanufacturer', models.CharField(max_length=35)),
                ('frametype', models.CharField(max_length=35)),
                ('frameadhesive', models.CharField(max_length=35)),
                ('encapsulatetype', models.CharField(max_length=35)),
                ('encapsulatemanufacturer', models.CharField(max_length=35)),
                ('junctionboxtype', models.CharField(max_length=35)),
                ('junctionboxmanufacturer', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=35)),
                ('isfirequired', models.CharField(max_length=35)),
                ('fifrequency', models.CharField(max_length=35)),
                ('standardid', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceid', models.CharField(max_length=35)),
                ('sequencename', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardname', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=35)),
                ('publisheddate', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('clientid', models.CharField(max_length=35)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('middlename', models.CharField(max_length=35)),
                ('jobtitle', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('officephone', models.CharField(max_length=35)),
                ('cellphone', models.CharField(max_length=35)),
                ('appellation', models.CharField(max_length=10)),
            ],
        ),
    ]
