# Generated by Django 3.0.5 on 2020-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='locationid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='modelnumber',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standardid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='userid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='location',
            name='clientid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='modelnumber',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='sequenceid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='service',
            name='standardid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='clientid',
            field=models.CharField(max_length=35),
        ),
    ]
